/**
 * Regression test — Task 4.9: v0.2.1 classic-path outbound parity
 *
 * Guards that the current build (HEAD) produces byte-identical outbound HTTP
 * to the v0.2.1 classic-credential path.
 *
 * The fixture `tests/fixtures/v021-send-capture.json` was generated by
 * `tests/regression/capture-v021.test.ts` (the capture harness) and records:
 *   - The Activity body sent to ConnectorClient.sendToConversation()
 *   - The conversation ID (which determines the URL path)
 *
 * Both v0.2.1 and current HEAD construct the same Activity object from the
 * same inputs and hand it to the SDK's ConnectorClient. This test ensures no
 * refactor in the auth router, bundle-cache, or send-operation path changes
 * that outbound shape.
 *
 * Stubs:
 *   - shared/auth/router → acquireOutboundToken returns a fixed bearer token
 *   - @microsoft/agents-hosting → ConnectorClient.createClientWithToken
 *     returns a spy client recording (conversationId, body)
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { IExecuteFunctions } from 'n8n-workflow';
import fixture from '../fixtures/v021-send-capture.json';
import type { M365ClassicBotCred } from '../../shared/types';

// ── Stubs ──────────────────────────────────────────────────────────────────────

vi.mock('../../shared/auth/router', () => ({
	acquireOutboundToken: vi.fn(async () => ({
		authorizationHeader: 'Bearer stub-bearer-token-for-parity',
	})),
	validateInboundToken: vi.fn(),
}));

const mockSendToConversation = vi.fn(async (_conversationId: string, _body: unknown) => ({
	id: 'parity-check-activity-id',
}));
const mockClient = { sendToConversation: mockSendToConversation };

vi.mock('@microsoft/agents-hosting', async (importOriginal) => {
	const original = await importOriginal<typeof import('@microsoft/agents-hosting')>();
	return {
		...original,
		ConnectorClient: {
			...original.ConnectorClient,
			createClientWithToken: vi.fn(() => mockClient),
		},
	};
});

// ── Fixed inputs (same as capture harness) ─────────────────────────────────────

const CONVERSATION_REFERENCE = {
	serviceUrl: fixture.inputs.serviceUrl,
	conversation: { id: fixture.inputs.conversationId, conversationType: 'personal' },
	channelId: 'msteams',
	activityId: '1700000000000',
};

const CREDENTIALS: M365ClassicBotCred = {
	appType: 'SingleTenant',
	clientId: 'test-client-id-parity',
	clientSecret: 'test-secret-parity',
	tenantId: 'test-tenant-id-parity',
};

// ── Helper ─────────────────────────────────────────────────────────────────────

function buildExecuteCtx(text: string) {
	const item = { json: { conversationReference: CONVERSATION_REFERENCE } };
	const params: Record<string, unknown> = {
		conversationSource: 'envelope',
		text,
		options: fixture.inputs.options,
		authKind: 'classicBot',
		identityMode: 'autonomous',
	};
	return {
		getInputData: () => [item],
		getNodeParameter: (name: string, _i: unknown, fallback?: unknown) =>
			name in params ? params[name] : fallback,
		getNode: () => ({
			id: 'parity-test-node',
			name: 'ParityTest',
			type: 'n8n-nodes-agents-sdk.m365Agent',
			typeVersion: 1,
			position: [0, 0] as [number, number],
			parameters: {},
		}),
		helpers: {
			constructExecutionMetaData: (d: unknown) => d,
			returnJsonArray: (d: unknown[]) => d.map((json) => ({ json })),
		},
		sendResponse: () => undefined,
	} as unknown as IExecuteFunctions;
}

// ── Tests ──────────────────────────────────────────────────────────────────────

describe('v0.2.1 classic-path outbound parity', () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it('calls sendToConversation with the v0.2.1-captured conversation ID', async () => {
		const { execute } = await import('../../nodes/M365Agent/actions/message/send.operation');

		const ctx = buildExecuteCtx(fixture.inputs.text);
		const bundles = new Map();

		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);

		expect(mockSendToConversation).toHaveBeenCalledOnce();
		const [conversationId] = mockSendToConversation.mock.calls[0];
		expect(conversationId).toBe(fixture.inputs.conversationId);
	});

	it('sends byte-identical Activity body to the v0.2.1 fixture', async () => {
		const { execute } = await import('../../nodes/M365Agent/actions/message/send.operation');

		const ctx = buildExecuteCtx(fixture.inputs.text);
		const bundles = new Map();

		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);

		expect(mockSendToConversation).toHaveBeenCalledOnce();
		const [, body] = mockSendToConversation.mock.calls[0];

		// Byte-identical: every field in the fixture body must match exactly.
		expect(body).toEqual(fixture.request.body);
	});

	it('constructs the correct URL pattern (v3/conversations/{id}/activities)', async () => {
		const { execute } = await import('../../nodes/M365Agent/actions/message/send.operation');

		const ctx = buildExecuteCtx(fixture.inputs.text);
		const bundles = new Map();

		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);

		expect(mockSendToConversation).toHaveBeenCalledOnce();
		const [conversationId] = mockSendToConversation.mock.calls[0];
		const actualUrlPattern = `v3/conversations/${conversationId}/activities`;
		expect(actualUrlPattern).toBe(fixture.request.urlPattern);
	});

	it('does not append workflowFooter when options is empty', async () => {
		const { execute } = await import('../../nodes/M365Agent/actions/message/send.operation');

		// Confirm options.workflowFooter=false → text is not modified
		const ctx = buildExecuteCtx(fixture.inputs.text);
		const bundles = new Map();

		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);

		const [, body] = mockSendToConversation.mock.calls[0] as [
			string,
			{ type: string; text: string },
		];
		expect(body.text).toBe(fixture.inputs.text);
		expect(body.text).not.toContain('Sent from n8n workflow');
	});

	it('uses classicBot auth path (acquireOutboundToken called once)', async () => {
		const { execute } = await import('../../nodes/M365Agent/actions/message/send.operation');
		const { acquireOutboundToken } = await import('../../shared/auth/router');

		const ctx = buildExecuteCtx(fixture.inputs.text);
		const bundles = new Map();

		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);

		expect(acquireOutboundToken).toHaveBeenCalledOnce();
		expect(acquireOutboundToken).toHaveBeenCalledWith(
			expect.objectContaining({ authKind: 'classicBot' }),
		);
	});

	it('caches the bundle — second call does not re-acquire token', async () => {
		const { execute } = await import('../../nodes/M365Agent/actions/message/send.operation');
		const { acquireOutboundToken } = await import('../../shared/auth/router');

		const ctx = buildExecuteCtx(fixture.inputs.text);
		const bundles = new Map();

		// Call twice with same bundles map (simulates two items in one execution)
		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);
		await execute.call(ctx, 0, 'classicBot', CREDENTIALS, bundles);

		// Token should only be acquired once — second call reuses cached bundle
		expect(acquireOutboundToken).toHaveBeenCalledOnce();
		expect(mockSendToConversation).toHaveBeenCalledTimes(2);
	});
});
